'use strict';

const CODES = Object.freeze({
    CHROME_LAUNCH_FAILED: 'CHROME_LAUNCH_FAILED',
    CHROME_PROTOCOL_ERROR: 'CHROME_PROTOCOL_ERROR',
    SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
    GOOGLE_LOGIN_REJECTED: 'GOOGLE_LOGIN_REJECTED',
    GOOGLE_LOGIN_STUCK: 'GOOGLE_LOGIN_STUCK',
    GOOGLE_CHALLENGE_UNSUPPORTED: 'GOOGLE_CHALLENGE_UNSUPPORTED',
    OAUTH_CODE_NOT_RECEIVED: 'OAUTH_CODE_NOT_RECEIVED',
    OAUTH_TOKEN_EXCHANGE_FAILED: 'OAUTH_TOKEN_EXCHANGE_FAILED',
    SMS_BALANCE_INSUFFICIENT: 'SMS_BALANCE_INSUFFICIENT',
    SMS_TIMEOUT: 'SMS_TIMEOUT',
    SMS_PROVIDER_ERROR: 'SMS_PROVIDER_ERROR',
    TOTP_INVALID_SECRET: 'TOTP_INVALID_SECRET',
    CONCURRENCY_LIMIT_EXCEEDED: 'CONCURRENCY_LIMIT_EXCEEDED',
    TIMEOUT: 'TIMEOUT',
    PRECONDITION_FAILED: 'PRECONDITION_FAILED',
});

class McpError extends Error {
    constructor(code, message, { cause } = {}) {
        super(message);
        this.name = 'McpError';
        this.code = code;
        if (cause) this.cause = cause;
    }
}

module.exports = { CODES, McpError };
